server:
  port: 9000

spring:
  cloud:
    config:
      server:
        git:
          uri: file:///home/darek/Devel/Spring/spring-io-lab14-config

management:
  endpoints:
    web:
      base-path: "/admin"
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
