spring:
  datasource:
    url: "jdbc:postgresql://${POSTGRES_PORT_5432_TCP_ADDR:localhost}:${POSTGRES_PORT_5432_TCP_PORT:5432}/warehouse"
    username: "postgres"
    password: "sprio"
  jpa:
    hibernate:
      ddl-auto: "validate"

management:
  endpoints:
    web:
      base-path: "/admin"
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      graphite:
        host: 172.17.0.2
        port: 2003

info:
  whatever: "hello"
